[build]
  command = "npm run build"
  publish = "public"  # Specify the directory where your built files are located

[build.environment]
  BASE_DIRECTORY = "/"  # Set the base directory to the root of your project

