[build]
  command = "npm run build"  # Specify the build command
  publish = "public"       # Specify the publish directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"