[build]
  command = "node app.js" # Adjust this command to start your server-side code

[[redirects]]
  from = "/tweet/*" # Define the route for your server-side function
  to = "/.netlify/functions/tweet" # Map the route to your serverless function
