[build]
  command = "node app.js"
  functions = "netlify/functions/"

[[redirects]]
  from = "/tweets/*"
  to = "./netlify/functions/tweet/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
