[build]
  command = "npm run build"
  publish = "public"  # Specify the correct publish directory where your built files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true


[[headers]]
for = "/*"

  [headers.values]
  Content-Type = "application/javascript"
  
[[headers]]
for = "/*"

  [headers.values]
  Content-Type = "application/json"
