[build]
  publish = "public"  # Specify the correct publish directory where your built files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true


[[headers]]
  for = "/*.js"  # Add this section to specify the JavaScript files
    [headers.values]
    Content-Type = "application/javascript"
