[build]
  command = "node app.js"
  functions = "netlify/functions/"

[[redirects]]
  from = "/tweets/*"
  to = "/tweets"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
