[build]
command = "npm run build"  # Specify the command to start your server
publish = "."            # Specify the publish directory (root of your project)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"